### ISSUE TITLE
API Gateway: Bumpy name for the apigateway-kibana-user secret

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-helm-charts#17]
It seems the name of this secret is {release_name}-{release_name}-apigateway-kibana-user. This looks a bit odd:

![image](https://github.com/SoftwareAG/webmethods-helm-charts/assets/20128287/183220ab-78cd-4b1c-9ed4-0da07e2a3a55)

**Comment by MarcFriedhoff** [comment]
@thesse1  is this still the case - should also be fixed with some changes we made with the secret handling.

**Comment by MarcFriedhoff** [comment]
@thesse1 Closing it - feel free to re-open if you still encounter this issue.

**Comment by thesse1** [comment]
Yes, it does still occur:

![image](https://github.com/SoftwareAG/webmethods-helm-charts/assets/20128287/0e3d4292-60ae-470b-9b78-ea48f1bd10c0)

**Comment by thesse1** [comment]
I cannot reopen this issue. Creating a new one...
